./debian/tmp/usr/bin/
./debian/tmp/usr/share/texmf/
./debian/tmp/usr/share/asymptote/*.asy
./debian/tmp/usr/share/asymptote/*.sh
./debian/tmp/usr/share/asymptote/*.py
./debian/tmp/usr/share/asymptote/*.ps
./debian/tmp/usr/share/asymptote/*.js
./debian/tmp/usr/share/asymptote/*.el	/usr/share/emacs/site-lisp/
./debian/tmp/usr/share/asymptote/asy_filetype.vim /usr/share/vim/addons/ftdetect/
./debian/tmp/usr/share/asymptote/asy.vim /usr/share/vim/addons/ftplugin/
./debian/tmp/usr/share/asymptote/shaders/*.glsl