#!/bin/sh
# preinst script for asymptote
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <new-preinst> `install'
#        * <new-preinst> `install' <old-version>
#        * <new-preinst> `upgrade' <old-version>
#        * <old-preinst> `abort-upgrade' <new-version>
#
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    install|upgrade)
      # remove old html directory (now moved to asymptote-doc) if it still
      # exists
      if [ -d /usr/share/doc/asymptote/html ] && [ ! -L /usr/share/doc/asymptote/html ]; then
	rm -rf /usr/share/doc/asymptote/html
      fi
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0


